version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: frontend
    ports:
      - '5001:5001'
    command:
      'npm run start'